font:
  family: [sans-serif]
  sans-serif:
    - Gotham
    - Helvetica Neue
    - Helvetica
    - Arial
    - sans-serif
  weight: 400
mathtext:
  default: regular
axes:
  facecolor: white
  grid: false
  edgecolor: black
  labelweight: 500
xtick:
  labelsize: small

